CREATE DATABASE todo_app;

USE todo_app;

CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE todos (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId VARCHAR(255) NOT NULL,
    todo LONGTEXT NOT NULL,
    completed TINYINT(1) NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(userId)
);
